name: CI Build & Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Check dotnet version
      run: dotnet --info

    - name: Build solution
      run: dotnet build SportsOdds.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test SportsOdds.sln --no-build --verbosity normal

    - name: Publish artifact
      run: dotnet publish Api/Api.csproj -c Release -o ./publish

    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: sports-odds-api
        path: ./publish
